scrape_configs:
  - job_name: 'user'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          application: 'user'
  - job_name: 'submitApplication'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'submitApplication'
  - job_name: 'review'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'review'
  - job_name: 'jobs'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          application: 'jobs'
  - job_name: 'company'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'company'